"""Points the console at /data-platform's static boundary tile artifacts.

Per ADR-001 (shared/contracts/ADR-001-map-tiles.md, contract v0.2.1):
boundary geometry (.pmtiles, generated by /data-platform) and prediction
scores (JSON, served by /backend) are two separate resources, joined
client-side via setFeatureState — never merged into one tile by the server.
/backend only returns a pointer URL to A's artifact (signed when required);
it never generates or proxies tile content.

GeoJSON is NOT used for standard administrative boundaries (sido/sigungu/
adm_dong) — those are always static .pmtiles. GeoJSON only appears inline in
the /predictions/{run_id}/scores response's `custom_geometries` field, for
tenant-defined custom_catchment regions.

A hasn't published real .pmtiles artifacts yet (data-platform/RECONCILIATION.md
§5 step 1 is still region-model work-in-progress), so `_VINTAGES` below is a
placeholder. Swap it for a real lookup once A ships boundary storage — the
manifest shape and signing contract stay the same.
"""

import hashlib
import hmac
import time
from dataclasses import dataclass

from app.config import settings

# Contract-fixed (04_api_contract.yaml v0.2.1): D keys setFeatureState on this.
FEATURE_ID_PROPERTY = "region_id"
SOURCE_LAYER = "regions"

_ZOOM_BY_LEVEL = {"sido": (5, 8), "sigungu": (5, 10), "adm_dong": (5, 12)}


@dataclass(frozen=True)
class TileArtifact:
    level: str
    boundary_vintage: str
    tile_url: str
    minzoom: int
    maxzoom: int
    attribution: str
    requires_signing: bool = False


def _artifacts_for(level: str, vintages: list[str]) -> list[TileArtifact]:
    minzoom, maxzoom = _ZOOM_BY_LEVEL[level]
    return [
        TileArtifact(
            level=level,
            boundary_vintage=vintage,
            tile_url=f"https://cdn.sellfinder.kr/tiles/regions-{level}-{vintage}.pmtiles",
            minzoom=minzoom,
            maxzoom=maxzoom,
            attribution="통계청 SGIS",
            requires_signing=(level == "adm_dong"),
        )
        for vintage in vintages
    ]


# level -> artifacts, newest vintage first ("latest" = index 0). A preserves
# every vintage rather than overwriting (ADR-001 "경계 빈티지" §1).
_VINTAGES: dict[str, list[TileArtifact]] = {
    "sido": _artifacts_for("sido", ["2026-01-01", "2025-01-01"]),
    "sigungu": _artifacts_for("sigungu", ["2026-01-01", "2025-01-01"]),
    "adm_dong": _artifacts_for("adm_dong", ["2026-01-01", "2025-01-01", "2024-01-01"]),
}


class UnknownVintageError(LookupError):
    pass


def sign_url(url: str) -> str:
    expires_at = int(time.time()) + settings.basemap_signed_url_ttl_seconds
    payload = f"{url}:{expires_at}".encode()
    signature = hmac.new(
        settings.basemap_signing_secret.encode(), payload, hashlib.sha256
    ).hexdigest()
    separator = "&" if "?" in url else "?"
    return f"{url}{separator}expires={expires_at}&sig={signature}"


def latest_vintage(level: str) -> str:
    return _VINTAGES[level][0].boundary_vintage


def get_manifest(level: str, vintage: str | None = None) -> dict:
    """Raises UnknownVintageError for an unknown level or vintage."""
    artifacts = _VINTAGES.get(level)
    if not artifacts:
        raise UnknownVintageError(f"알 수 없는 level: {level}")

    if vintage is None:
        artifact = artifacts[0]
    else:
        artifact = next((a for a in artifacts if a.boundary_vintage == vintage), None)
        if artifact is None:
            raise UnknownVintageError(
                f"level '{level}'에 vintage '{vintage}' 아티팩트가 없습니다. "
                f"available_vintages={[a.boundary_vintage for a in artifacts]}"
            )

    tile_url = sign_url(artifact.tile_url) if artifact.requires_signing else artifact.tile_url

    return {
        "level": artifact.level,
        "boundary_vintage": artifact.boundary_vintage,
        "tile_url": tile_url,
        "source_layer": SOURCE_LAYER,
        "feature_id_property": FEATURE_ID_PROPERTY,
        "minzoom": artifact.minzoom,
        "maxzoom": artifact.maxzoom,
        "attribution": artifact.attribution,
        "available_vintages": [a.boundary_vintage for a in artifacts],
    }
