"""Points the console at /data-platform's static boundary tile artifacts.

Per ADR-001 (shared/contracts/ADR-001-map-tiles.md, contract v0.2.1/v0.2.2):
boundary geometry (.pmtiles, generated by /data-platform) and prediction
scores (JSON, served by /backend) are two separate resources, joined
client-side via setFeatureState — never merged into one tile by the server.
/backend only returns a pointer URL to A's artifact (signed when required);
it never generates or proxies tile content.

GeoJSON is NOT used for standard administrative boundaries (sido/sigungu/
adm_dong) — those are always static .pmtiles. GeoJSON only appears inline in
the /predictions/{run_id}/scores response's `custom_geometries` field, for
tenant-defined custom_catchment regions.

ADR-002 결정 3 (VF-004): level/vintage/zoom/feature_id_property used to be
hardcoded here and drifted from what A actually publishes (a 3-level fake
vintage table vs. A's real 1-level, 2-vintage output). That is gone. Every
per-artifact field below is read straight from A's own manifest files —
never invented — from two git-tracked sources (D-11: gitignored
data-platform/output/tiles/* is producer-local and must never be read here):

  1. data-platform/output/manifest/regions-{level}-{vintage}.json
     (A's real published output, one file per level+vintage, D-13)
  2. data-platform/fixtures/manifest-fixture.json
     (A's sigungu dev fixture, D-12 — the one sanctioned stand-in, used
     only because no real sigungu output exists yet)

If a level has no file from either source, get_manifest/latest_vintage
raise NoBoundaryArtifactsError. The router turns that into 503 + a reason —
an empty available_vintages list would be a false "no vintages exist"
signal (ADR-002).
"""

import glob
import hashlib
import hmac
import json
import time
from dataclasses import dataclass
from pathlib import Path

from app.config import settings

_REPO_ROOT = Path(__file__).resolve().parents[3]
_MANIFEST_GLOB = str(_REPO_ROOT / "data-platform" / "output" / "manifest" / "regions-*.json")
_FIXTURE_MANIFEST = _REPO_ROOT / "data-platform" / "fixtures" / "manifest-fixture.json"

# Not sourced from A's manifest — A doesn't publish a signing policy, this is
# a /backend product decision about which level's artifacts sit behind a
# signed URL. Only remaining level-keyed lookup in this file; unlike
# _VINTAGES/_ZOOM_BY_LEVEL/FEATURE_ID_PROPERTY (removed, DISPATCH C-7) it
# carries no geometry/zoom/vintage data that could drift from A's output.
_SIGNED_LEVELS = {"adm_dong"}

_REQUIRED_MANIFEST_KEYS = (
    "level",
    "boundary_vintage",
    "tile_url",
    "source_layer",
    "feature_id_property",
    "minzoom",
    "maxzoom",
    "attribution",
)


@dataclass(frozen=True)
class TileArtifact:
    level: str
    boundary_vintage: str
    tile_url: str
    source_layer: str
    feature_id_property: str
    minzoom: int
    maxzoom: int
    attribution: str


class UnknownVintageError(LookupError):
    """Level exists but the requested vintage doesn't."""


class NoBoundaryArtifactsError(LookupError):
    """No manifest file at all for this level (ADR-002 결정 3 / D-13)."""


def _artifact_files() -> list[Path]:
    files = [Path(p) for p in glob.glob(_MANIFEST_GLOB)]
    if _FIXTURE_MANIFEST.exists():
        files.append(_FIXTURE_MANIFEST)
    return files


def _load_artifacts() -> dict[str, list[TileArtifact]]:
    """Re-reads from disk on every call (no in-process cache): these files
    are how A hands off new publishes, and a long-lived cache would mean a
    republish never reaches C without a restart."""
    by_level: dict[str, list[TileArtifact]] = {}
    for path in _artifact_files():
        data = json.loads(path.read_text(encoding="utf-8"))
        missing = [k for k in _REQUIRED_MANIFEST_KEYS if k not in data]
        if missing:
            raise ValueError(f"{path}: A의 매니페스트에 필수 키 누락: {missing}")
        artifact = TileArtifact(**{k: data[k] for k in _REQUIRED_MANIFEST_KEYS})
        by_level.setdefault(artifact.level, []).append(artifact)

    for artifacts in by_level.values():
        # D-12's "fixture" pseudo-vintage sorts after real dated vintages
        # even though the bare string "fixture" > any "YYYY-MM-DD" string
        # lexically — sigungu can now have both (A published real
        # 2026-01-01 sigungu output after the fixture already existed), and
        # the synthetic placeholder must never present itself as "latest".
        artifacts.sort(
            key=lambda a: (a.boundary_vintage != "fixture", a.boundary_vintage),
            reverse=True,
        )

    return by_level


def sign_url(url: str) -> str:
    expires_at = int(time.time()) + settings.basemap_signed_url_ttl_seconds
    payload = f"{url}:{expires_at}".encode()
    signature = hmac.new(
        settings.basemap_signing_secret.encode(), payload, hashlib.sha256
    ).hexdigest()
    separator = "&" if "?" in url else "?"
    return f"{url}{separator}expires={expires_at}&sig={signature}"


def latest_vintage(level: str) -> str:
    artifacts = _load_artifacts().get(level)
    if not artifacts:
        raise NoBoundaryArtifactsError(level)
    return artifacts[0].boundary_vintage


def get_manifest(level: str, vintage: str | None = None) -> dict:
    """Raises NoBoundaryArtifactsError if A hasn't published this level at
    all, UnknownVintageError if the level exists but not that vintage."""
    artifacts = _load_artifacts().get(level)
    if not artifacts:
        raise NoBoundaryArtifactsError(level)

    if vintage is None:
        artifact = artifacts[0]
    else:
        artifact = next((a for a in artifacts if a.boundary_vintage == vintage), None)
        if artifact is None:
            raise UnknownVintageError(
                f"level '{level}'에 vintage '{vintage}' 아티팩트가 없습니다. "
                f"available_vintages={[a.boundary_vintage for a in artifacts]}"
            )

    tile_url = sign_url(artifact.tile_url) if level in _SIGNED_LEVELS else artifact.tile_url

    return {
        "level": artifact.level,
        "boundary_vintage": artifact.boundary_vintage,
        "tile_url": tile_url,
        "source_layer": artifact.source_layer,
        "feature_id_property": artifact.feature_id_property,
        "minzoom": artifact.minzoom,
        "maxzoom": artifact.maxzoom,
        "attribution": artifact.attribution,
        "available_vintages": [a.boundary_vintage for a in artifacts],
    }
